### ISSUE TITLE
Win10 binary not start

### ISSUE THREAD

**Issue by tctfcrazzy** [jkotra/wpc#8]
Not start at Win10
`D:\>wpc.exe -d D:/Pic/ -w -u 360 --startup
Trying to add WPC to startup...
WPC added to startup!
thread 'main' panicked at 'not currently running on the Tokio runtime.', C:\Users\synk\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.13\src\runtime\handle.rs:63:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

`D:\>wpc.exe -V
WPC 0.7.5`
Downloaded binary from releases page

**Comment by jkotra** [comment]
Thanks for reporting the bug @tctfcrazzy .

This bug was introduced in 0.7.5 caused due upgrading `tokio` to 1.0 which lead to inter-dependency mismatch. This has been fixed in 30e624ba927f3c186117f3b8d54764db0c4e63d0 and 46f4f90509f5eaff0cb5636b33f7a620506b4865 along with few other leftover bug fixes.

I released 0.7.6 - https://github.com/jkotra/wpc/releases/tag/0.7.6

If you encounter any problems, please report :bug: 

Thank you.

**Comment by tctfcrazzy** [comment]
Works great, thanks.
